---
name: Parse-HTTP-UserAgent
version: 0.10
author:
  - 'Burak Gursoy <burak@cpan.org>'
abstract: Parser for the User Agent string
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-parse-http-useragent/
build_requires:
  Test::More: 0.40
requires:
  version: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Parse::HTTP::UserAgent:
    file: lib/Parse/HTTP/UserAgent.pm
    version: 0.10
  Parse::HTTP::UserAgent::Constants:
    file: lib/Parse/HTTP/UserAgent/Constants.pm
    version: 0.10
  Parse::HTTP::UserAgent::Dumper:
    file: lib/Parse/HTTP/UserAgent/Dumper.pm
    version: 0.10
  Parse::HTTP::UserAgent::IS:
    file: lib/Parse/HTTP/UserAgent/IS.pm
    version: 0.10
  Parse::HTTP::UserAgent::Parsers:
    file: lib/Parse/HTTP/UserAgent/Parsers.pm
    version: 0.10
no_index:
  directory:
    - monolithic_version
    - builder
    - t
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
